resolver: lts-16.2

packages:
- messdb-base
- messdb-base-testlib
- messdb-repo
- messdb-schema
- messdb-sql
- messdb-store-lmdb
- messdb-store-sqlite
- messdb-tool

extra-deps:
- simple-sql-parser-0.6.0
